export function getPrimeNGIconFromMimeType(mimeType: string) {
    const iconMap: Object = {
        'application/pdf': 'pi pi-file-pdf pdf-icon',
        'image/jpeg': 'pi pi-image image-icon',
        'image/png': 'pi pi-image image-icon',
        'image/webp': 'pi pi-image image-icon',
        'image/gif': 'pi pi-image image-icon',
        'text/plain': 'pi pi-file',
        'application/msword': 'pi pi-file-word word-icon',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'pi pi-file-word word-icon',
        'application/vnd.ms-excel': 'pi pi-file-excel excel-icon',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'pi pi-file-excel excel-icon',
        'text/csv': 'pi pi-file-excel excel-icon',
        'application/vnd.ms-powerpoint': 'pi pi-file-powerpoint powerpoint-icon',
        "audio/mp3": "pi pi-volume-up",
        "video/mp4": "pi pi-video",
        "application/zip": "pi pi-file-archive",
        "application/json": "pi pi-code",
        "text/html": "pi pi-code",
        "application/xml": "pi pi-code",
        "application/javascript": "pi pi-code",
        "text/css": "pi pi-code",
        "application/sql": "pi pi-code",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pi pi-file-powerpoint",
        "audio/wav": "pi pi-volume-up",
        "audio/mpeg": "pi pi-volume-up",
        "video/mpeg": "pi pi-video",
        "video/quicktime": "pi pi-video",
        "image/bmp": "pi pi-image",
        "application/vnd.android.package-archive": "pi pi-file-archive",
        "application/x-rar-compressed": "pi pi-file-archive",
        "application/x-tar": "pi pi-file-archive",
        "application/x-7z-compressed": "pi pi-file-archive",
        "application/x-gzip": "pi pi-file-archive",
        "application/vnd.ms-access": "pi pi-file-database",
        "application/x-yaml": "pi pi-code",
        "application/vnd.oasis.opendocument.text": "pi pi-file-word",
        "application/vnd.oasis.opendocument.spreadsheet": "pi pi-excel",
        "application/vnd.oasis.opendocument.presentation": "pi pi-powerpoint",
        "application/x-dvi": "pi pi-code",
        "application/vnd.visio": "pi pi-powerpoint",
        "application/x-shockwave-flash": "pi pi-video",
        "application/x-msdownload": "pi pi-file-archive",
        "application/vnd.apple.installer+xml": "pi pi-file-archive",
        "application/x-pkcs12": "pi pi-file-archive",
        "application/x-rar": "pi pi-file-archive",
        "application/x-stuffit": "pi pi-file-archive",
        "application/vnd.rar": "pi pi-file-archive",
        "application/x-tex": "pi pi-code",
        "application/x-texinfo": "pi pi-code",
        "application/x-tex-tfm": "pi pi-code",
        "application/x-tex-dvi": "pi pi-code",
        "application/x-latex": "pi pi-code",
        "application/x-font-ttf": "pi pi-code",
        "application/x-font-woff": "pi pi-code",
        "application/x-font-woff2": "pi pi-code",
        "application/vnd.ms-fontobject": "pi pi-code",
        "application/font-woff": "pi pi-code",
        "application/font-woff2": "pi pi-code",
        "application/vnd.ms-opentype": "pi pi-code",
        "application/x-font-opentype": "pi pi-code",
        "application/x-font-otf": "pi pi-code",
        "application/x-font-truetype": "pi pi-code",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template": "pi pi-file-word",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template": "pi pi-file-excel",
        "application/vnd.openxmlformats-officedocument.presentationml.template": "pi pi-file-powerpoint",
        "application/vnd.apple.pages": "pi pi-file-word",
        "application/vnd.apple.numbers": "pi pi-file-excel",
        "application/vnd.apple.keynote": "pi pi-file-powerpoint",
        // Add more MIME types and corresponding icons as needed
    };

    // Use the iconMap to look up the PrimeNG icon for the given MIME type
    const icon: any = iconMap[mimeType as keyof Object];

    // If a matching icon is found, return it; otherwise, return a default icon
    return icon ? icon : 'pi pi-file';
}